// auto-generated by creative refresh
// last_updated: 2026-07-29

const CREATIVE_DATA = {
  "meta": {
    "lastUpdated": "2026-07-29",
    "queryStart": "2026-05-01",
    "queryEnd": "2026-07-29"
  },
  "summary": {
    "totalCostMan": 11557.0,
    "totalRevenueMan": 138732,
    "blendRoas": 1200,
    "totalCnt": 19378
  },
  "groups": ["diorama-2605", "blacklabel-2605", "stressfree-2605", "tf-2606"],
  "creatives": [
    {
      "id": "diorama-jejuterminal",
      "name": "jejuterminal",
      "group": "diorama-2605",
      "badge": "최고 효율",
      "roas": 1972,
      "revenueMan": 12314,
      "costMan": 624.4,
      "cnt": 1805,
      "valuePerCnt": 68222,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-28",
      "days": 45,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 84 },
        { "name": "Facebook", "cls": "fb", "pct": 16 }
      ]
    },
    {
      "id": "diorama-mart",
      "name": "mart",
      "group": "diorama-2605",
      "badge": "양호",
      "roas": 1642,
      "revenueMan": 3514,
      "costMan": 214.1,
      "cnt": 527,
      "valuePerCnt": 66682,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-29",
      "days": 46,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 70 },
        { "name": "Facebook", "cls": "fb", "pct": 30 }
      ]
    },
    {
      "id": "diorama-season",
      "name": "season",
      "group": "diorama-2605",
      "badge": "양호",
      "roas": 1473,
      "revenueMan": 2652,
      "costMan": 180.0,
      "cnt": 416,
      "valuePerCnt": 63741,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-28",
      "days": 45,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 64 },
        { "name": "Facebook", "cls": "fb", "pct": 36 }
      ]
    },
    {
      "id": "diorama-camping",
      "name": "camping",
      "group": "diorama-2605",
      "badge": "모니터링",
      "roas": 534,
      "revenueMan": 845,
      "costMan": 158.3,
      "cnt": 133,
      "valuePerCnt": 63504,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-29",
      "days": 46,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 71 },
        { "name": "Facebook", "cls": "fb", "pct": 26 },
        { "name": "Moloco", "cls": "", "pct": 3 }
      ]
    },
    {
      "id": "blacklabel-palace",
      "name": "palace",
      "group": "blacklabel-2605",
      "badge": "모니터링",
      "roas": 906,
      "revenueMan": 4118,
      "costMan": 454.3,
      "cnt": 706,
      "valuePerCnt": 58322,
      "firstDate": "2026-05-01",
      "lastDate": "2026-07-11",
      "days": 72,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 91 },
        { "name": "Facebook", "cls": "fb", "pct": 9 }
      ]
    },
    {
      "id": "blacklabel-drive",
      "name": "drive",
      "group": "blacklabel-2605",
      "badge": "볼륨 1위",
      "roas": 1187,
      "revenueMan": 29056,
      "costMan": 2448.7,
      "cnt": 3848,
      "valuePerCnt": 75510,
      "firstDate": "2026-05-01",
      "lastDate": "2026-07-28",
      "days": 89,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 98 },
        { "name": "Facebook", "cls": "fb", "pct": 2 }
      ]
    },
    {
      "id": "blacklabel-pinlight",
      "name": "pinlight",
      "group": "blacklabel-2605",
      "badge": "모니터링",
      "roas": 709,
      "revenueMan": 11375,
      "costMan": 1603.5,
      "cnt": 1690,
      "valuePerCnt": 67306,
      "firstDate": "2026-05-01",
      "lastDate": "2026-07-28",
      "days": 89,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 84 },
        { "name": "Facebook", "cls": "fb", "pct": 16 }
      ]
    },
    {
      "id": "blacklabel-parkinglot",
      "name": "parkinglot",
      "group": "blacklabel-2605",
      "badge": "중단 · 참고용",
      "roas": 3216,
      "revenueMan": 1755,
      "costMan": 54.6,
      "cnt": 165,
      "valuePerCnt": 106390,
      "firstDate": "2026-05-01",
      "lastDate": "2026-05-25",
      "days": 25,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 100 }
      ]
    },
    {
      "id": "stressfree",
      "name": "stressfree",
      "group": "stressfree-2605",
      "badge": "양호",
      "roas": 1594,
      "revenueMan": 13659,
      "costMan": 856.7,
      "cnt": 2293,
      "valuePerCnt": 59566,
      "firstDate": "2026-05-12",
      "lastDate": "2026-07-09",
      "days": 59,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 68 },
        { "name": "TikTok", "cls": "tt", "pct": 32 }
      ],
      "mediaNote": "(TT 5/27 중단)"
    },
    {
      "id": "tf-blacklabel-kv",
      "name": "blacklabel_kv",
      "group": "tf-2606",
      "badge": "양호",
      "roas": 1816,
      "revenueMan": 15991,
      "costMan": 880.6,
      "cnt": 2146,
      "valuePerCnt": 74515,
      "firstDate": "2026-06-16",
      "lastDate": "2026-07-28",
      "days": 43,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 84 },
        { "name": "Facebook", "cls": "fb", "pct": 16 }
      ]
    },
    {
      "id": "tf-car-olive",
      "name": "car_olive",
      "group": "tf-2606",
      "badge": "양호",
      "roas": 1001,
      "revenueMan": 11487,
      "costMan": 1147.8,
      "cnt": 1445,
      "valuePerCnt": 79495,
      "firstDate": "2026-06-23",
      "lastDate": "2026-07-28",
      "days": 36,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 100 }
      ]
    },
    {
      "id": "tf-blacklabel-car",
      "name": "blacklabel_car",
      "group": "tf-2606",
      "badge": "모니터링",
      "roas": 817,
      "revenueMan": 6574,
      "costMan": 804.1,
      "cnt": 805,
      "valuePerCnt": 81660,
      "firstDate": "2026-07-01",
      "lastDate": "2026-07-28",
      "days": 28,
      "media": [
        { "name": "Moloco", "cls": "", "pct": 57 },
        { "name": "TikTok", "cls": "tt", "pct": 43 }
      ]
    },
    {
      "id": "tf-delivery",
      "name": "delivery",
      "group": "tf-2606",
      "badge": "모니터링",
      "roas": 922,
      "revenueMan": 8471,
      "costMan": 918.8,
      "cnt": 1047,
      "valuePerCnt": 80903,
      "firstDate": "2026-07-01",
      "lastDate": "2026-07-28",
      "days": 28,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 52 },
        { "name": "Moloco", "cls": "", "pct": 48 }
      ]
    },
    {
      "id": "tf-movie-gatsby",
      "name": "movie_gatsby",
      "group": "tf-2606",
      "badge": "양호",
      "roas": 1572,
      "revenueMan": 9230,
      "costMan": 587.0,
      "cnt": 1146,
      "valuePerCnt": 80540,
      "firstDate": "2026-07-02",
      "lastDate": "2026-07-28",
      "days": 27,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 91 },
        { "name": "TikTok", "cls": "tt", "pct": 9 }
      ]
    },
    {
      "id": "tf-movie-toy",
      "name": "movie_toy",
      "group": "tf-2606",
      "badge": "양호",
      "roas": 1559,
      "revenueMan": 3254,
      "costMan": 208.7,
      "cnt": 512,
      "valuePerCnt": 63547,
      "firstDate": "2026-07-02",
      "lastDate": "2026-07-28",
      "days": 27,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 88 },
        { "name": "TikTok", "cls": "tt", "pct": 12 }
      ]
    },
    {
      "id": "tf-movie-sketch",
      "name": "movie_sketch",
      "group": "tf-2606",
      "badge": "모니터링",
      "roas": 933,
      "revenueMan": 566,
      "costMan": 60.7,
      "cnt": 86,
      "valuePerCnt": 65812,
      "firstDate": "2026-07-02",
      "lastDate": "2026-07-28",
      "days": 27,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 82 },
        { "name": "TikTok", "cls": "tt", "pct": 18 }
      ]
    },
    {
      "id": "tf-movie-bladerunner",
      "name": "movie_bladerunner",
      "group": "tf-2606",
      "badge": "양호",
      "roas": 1050,
      "revenueMan": 1957,
      "costMan": 186.5,
      "cnt": 334,
      "valuePerCnt": 58607,
      "firstDate": "2026-07-02",
      "lastDate": "2026-07-28",
      "days": 27,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 80 },
        { "name": "TikTok", "cls": "tt", "pct": 20 }
      ]
    },
    {
      "id": "tf-movie-minor",
      "name": "movie_minor",
      "group": "tf-2606",
      "badge": "양호",
      "roas": 1138,
      "revenueMan": 1914,
      "costMan": 168.2,
      "cnt": 274,
      "valuePerCnt": 69848,
      "firstDate": "2026-07-02",
      "lastDate": "2026-07-28",
      "days": 27,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 86 },
        { "name": "TikTok", "cls": "tt", "pct": 14 }
      ]
    }
  ]
};
