// auto-generated by creative refresh
// last_updated: 2026-06-30

const CREATIVE_DATA = {
  "meta": {
    "lastUpdated": "2026-06-30",
    "queryStart": "2026-05-01",
    "queryEnd": "2026-06-30"
  },
  "summary": {
    "totalCostMan": 5584.4,
    "totalRevenueMan": 73370,
    "blendRoas": 1314,
    "totalCnt": 10900
  },
  "groups": ["diorama-2605", "blacklabel-2605", "stressfree-2605"],
  "creatives": [
    {
      "id": "diorama-jejuterminal",
      "name": "jejuterminal",
      "group": "diorama-2605",
      "badge": "최고 효율",
      "roas": 1972,
      "revenueMan": 12314,
      "costMan": 624.4,
      "cnt": 1805,
      "valuePerCnt": 68222,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-28",
      "days": 45,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 84 },
        { "name": "Facebook", "cls": "fb", "pct": 16 }
      ]
    },
    {
      "id": "diorama-mart",
      "name": "mart",
      "group": "diorama-2605",
      "badge": "양호",
      "roas": 1642,
      "revenueMan": 3514,
      "costMan": 214.1,
      "cnt": 527,
      "valuePerCnt": 66682,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-28",
      "days": 45,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 70 },
        { "name": "Facebook", "cls": "fb", "pct": 30 }
      ]
    },
    {
      "id": "diorama-season",
      "name": "season",
      "group": "diorama-2605",
      "badge": "양호",
      "roas": 1473,
      "revenueMan": 2652,
      "costMan": 180.0,
      "cnt": 416,
      "valuePerCnt": 63741,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-28",
      "days": 45,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 64 },
        { "name": "Facebook", "cls": "fb", "pct": 36 }
      ]
    },
    {
      "id": "diorama-camping",
      "name": "camping",
      "group": "diorama-2605",
      "badge": "모니터링",
      "roas": 534,
      "revenueMan": 845,
      "costMan": 158.3,
      "cnt": 133,
      "valuePerCnt": 63504,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-28",
      "days": 45,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 71 },
        { "name": "Facebook", "cls": "fb", "pct": 26 },
        { "name": "Moloco", "cls": "", "pct": 3 }
      ]
    },
    {
      "id": "blacklabel-palace",
      "name": "palace",
      "group": "blacklabel-2605",
      "badge": "양호",
      "roas": 940,
      "revenueMan": 4118,
      "costMan": 438.1,
      "cnt": 706,
      "valuePerCnt": 58322,
      "firstDate": "2026-05-01",
      "lastDate": "2026-06-28",
      "days": 59,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 90 },
        { "name": "Facebook", "cls": "fb", "pct": 10 }
      ]
    },
    {
      "id": "blacklabel-drive",
      "name": "drive",
      "group": "blacklabel-2605",
      "badge": "볼륨 1위",
      "roas": 1299,
      "revenueMan": 24149,
      "costMan": 1859.0,
      "cnt": 3299,
      "valuePerCnt": 73201,
      "firstDate": "2026-05-01",
      "lastDate": "2026-06-28",
      "days": 59,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 97 },
        { "name": "Facebook", "cls": "fb", "pct": 3 }
      ]
    },
    {
      "id": "blacklabel-pinlight",
      "name": "pinlight",
      "group": "blacklabel-2605",
      "badge": "모니터링",
      "roas": 886,
      "revenueMan": 10935,
      "costMan": 1233.8,
      "cnt": 1641,
      "valuePerCnt": 66634,
      "firstDate": "2026-05-01",
      "lastDate": "2026-06-28",
      "days": 59,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 79 },
        { "name": "Facebook", "cls": "fb", "pct": 21 }
      ]
    },
    {
      "id": "blacklabel-parkinglot",
      "name": "parkinglot",
      "group": "blacklabel-2605",
      "badge": "중단 · 참고용",
      "roas": 3216,
      "revenueMan": 1755,
      "costMan": 54.6,
      "cnt": 165,
      "valuePerCnt": 106390,
      "firstDate": "2026-05-01",
      "lastDate": "2026-05-25",
      "days": 25,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 100 }
      ]
    },
    {
      "id": "stressfree",
      "name": "stressfree",
      "group": "stressfree-2605",
      "badge": "양호",
      "roas": 1592,
      "revenueMan": 13088,
      "costMan": 822.1,
      "cnt": 2208,
      "valuePerCnt": 59273,
      "firstDate": "2026-05-12",
      "lastDate": "2026-06-28",
      "days": 48,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 67 },
        { "name": "TikTok", "cls": "tt", "pct": 33 }
      ],
      "mediaNote": "(TT 5/27 중단)"
    }
  ]
};
