// auto-generated by creative refresh
// last_updated: 2026-07-10

const CREATIVE_DATA = {
  "meta": {
    "lastUpdated": "2026-07-10",
    "queryStart": "2026-05-01",
    "queryEnd": "2026-07-09"
  },
  "summary": {
    "totalCostMan": 8584.4,
    "totalRevenueMan": 78428,
    "blendRoas": 914,
    "totalCnt": 13308
  },
  "groups": ["diorama-2605", "blacklabel-2605", "stressfree-2605", "tf-2606"],
  "creatives": [
    {
      "id": "diorama-jejuterminal",
      "name": "jejuterminal",
      "group": "diorama-2605",
      "badge": "최고 효율",
      "roas": 1511,
      "revenueMan": 9431,
      "costMan": 624.4,
      "cnt": 1689,
      "valuePerCnt": 55839,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-28",
      "days": 45,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 84 },
        { "name": "Facebook", "cls": "fb", "pct": 16 }
      ]
    },
    {
      "id": "diorama-mart",
      "name": "mart",
      "group": "diorama-2605",
      "badge": "양호",
      "roas": 1405,
      "revenueMan": 3008,
      "costMan": 214.1,
      "cnt": 522,
      "valuePerCnt": 57663,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-29",
      "days": 46,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 70 },
        { "name": "Facebook", "cls": "fb", "pct": 30 }
      ]
    },
    {
      "id": "diorama-season",
      "name": "season",
      "group": "diorama-2605",
      "badge": "양호",
      "roas": 1218,
      "revenueMan": 2193,
      "costMan": 180.0,
      "cnt": 399,
      "valuePerCnt": 54962,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-28",
      "days": 45,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 64 },
        { "name": "Facebook", "cls": "fb", "pct": 36 }
      ]
    },
    {
      "id": "diorama-camping",
      "name": "camping",
      "group": "diorama-2605",
      "badge": "모니터링",
      "roas": 377,
      "revenueMan": 597,
      "costMan": 158.3,
      "cnt": 116,
      "valuePerCnt": 51466,
      "firstDate": "2026-05-15",
      "lastDate": "2026-06-29",
      "days": 46,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 71 },
        { "name": "Facebook", "cls": "fb", "pct": 26 },
        { "name": "Moloco", "cls": "", "pct": 3 }
      ]
    },
    {
      "id": "blacklabel-palace",
      "name": "palace",
      "group": "blacklabel-2605",
      "badge": "모니터링",
      "roas": 705,
      "revenueMan": 3202,
      "costMan": 454.3,
      "cnt": 610,
      "valuePerCnt": 52492,
      "firstDate": "2026-05-01",
      "lastDate": "2026-07-09",
      "days": 70,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 91 },
        { "name": "Facebook", "cls": "fb", "pct": 9 }
      ]
    },
    {
      "id": "blacklabel-drive",
      "name": "drive",
      "group": "blacklabel-2605",
      "badge": "볼륨 1위",
      "roas": 992,
      "revenueMan": 21440,
      "costMan": 2162.6,
      "cnt": 3293,
      "valuePerCnt": 65113,
      "firstDate": "2026-05-01",
      "lastDate": "2026-07-09",
      "days": 70,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 97 },
        { "name": "Facebook", "cls": "fb", "pct": 3 }
      ]
    },
    {
      "id": "blacklabel-pinlight",
      "name": "pinlight",
      "group": "blacklabel-2605",
      "badge": "모니터링",
      "roas": 684,
      "revenueMan": 9732,
      "costMan": 1423.4,
      "cnt": 1679,
      "valuePerCnt": 57963,
      "firstDate": "2026-05-01",
      "lastDate": "2026-07-09",
      "days": 70,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 80 },
        { "name": "Facebook", "cls": "fb", "pct": 20 }
      ]
    },
    {
      "id": "blacklabel-parkinglot",
      "name": "parkinglot",
      "group": "blacklabel-2605",
      "badge": "중단 · 참고용",
      "roas": 1791,
      "revenueMan": 978,
      "costMan": 54.6,
      "cnt": 116,
      "valuePerCnt": 84310,
      "firstDate": "2026-05-01",
      "lastDate": "2026-05-25",
      "days": 25,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 100 }
      ]
    },
    {
      "id": "stressfree",
      "name": "stressfree",
      "group": "stressfree-2605",
      "badge": "양호",
      "roas": 1218,
      "revenueMan": 10428,
      "costMan": 856.7,
      "cnt": 2069,
      "valuePerCnt": 50400,
      "firstDate": "2026-05-12",
      "lastDate": "2026-07-09",
      "days": 59,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 68 },
        { "name": "TikTok", "cls": "tt", "pct": 32 }
      ],
      "mediaNote": "(TT 5/27 중단)"
    },
    {
      "id": "tf-blacklabel-kv",
      "name": "blacklabel_kv",
      "group": "tf-2606",
      "badge": "양호",
      "roas": 1198,
      "revenueMan": 8421,
      "costMan": 703.0,
      "cnt": 1355,
      "valuePerCnt": 62141,
      "firstDate": "2026-06-16",
      "lastDate": "2026-07-09",
      "days": 24,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 80 },
        { "name": "Facebook", "cls": "fb", "pct": 20 }
      ]
    },
    {
      "id": "tf-car-olive",
      "name": "car_olive",
      "group": "tf-2606",
      "badge": "모니터링",
      "roas": 590,
      "revenueMan": 4026,
      "costMan": 682.4,
      "cnt": 667,
      "valuePerCnt": 60359,
      "firstDate": "2026-06-23",
      "lastDate": "2026-07-09",
      "days": 17,
      "media": [
        { "name": "TikTok", "cls": "tt", "pct": 100 }
      ]
    },
    {
      "id": "tf-blacklabel-car",
      "name": "blacklabel_car",
      "group": "tf-2606",
      "badge": "모니터링",
      "roas": 405,
      "revenueMan": 1317,
      "costMan": 325.0,
      "cnt": 162,
      "valuePerCnt": 81296,
      "firstDate": "2026-07-01",
      "lastDate": "2026-07-09",
      "days": 9,
      "media": [
        { "name": "Moloco", "cls": "", "pct": 71 },
        { "name": "TikTok", "cls": "tt", "pct": 29 }
      ]
    },
    {
      "id": "tf-delivery",
      "name": "delivery",
      "group": "tf-2606",
      "badge": "모니터링",
      "roas": 256,
      "revenueMan": 534,
      "costMan": 208.8,
      "cnt": 69,
      "valuePerCnt": 77391,
      "firstDate": "2026-07-01",
      "lastDate": "2026-07-09",
      "days": 9,
      "media": [
        { "name": "Moloco", "cls": "", "pct": 94 },
        { "name": "TikTok", "cls": "tt", "pct": 6 }
      ]
    },
    {
      "id": "tf-movie-gatsby",
      "name": "movie_gatsby",
      "group": "tf-2606",
      "badge": "양호",
      "roas": 553,
      "revenueMan": 914,
      "costMan": 165.3,
      "cnt": 154,
      "valuePerCnt": 59351,
      "firstDate": "2026-07-02",
      "lastDate": "2026-07-09",
      "days": 8,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 70 },
        { "name": "TikTok", "cls": "tt", "pct": 30 }
      ]
    },
    {
      "id": "tf-movie-toy",
      "name": "movie_toy",
      "group": "tf-2606",
      "badge": "양호",
      "roas": 716,
      "revenueMan": 728,
      "costMan": 101.7,
      "cnt": 123,
      "valuePerCnt": 59187,
      "firstDate": "2026-07-02",
      "lastDate": "2026-07-09",
      "days": 8,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 79 },
        { "name": "TikTok", "cls": "tt", "pct": 21 }
      ]
    },
    {
      "id": "tf-movie-sketch",
      "name": "movie_sketch",
      "group": "tf-2606",
      "badge": "모니터링",
      "roas": 510,
      "revenueMan": 171,
      "costMan": 33.5,
      "cnt": 35,
      "valuePerCnt": 48857,
      "firstDate": "2026-07-02",
      "lastDate": "2026-07-09",
      "days": 8,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 82 },
        { "name": "TikTok", "cls": "tt", "pct": 18 }
      ]
    },
    {
      "id": "tf-movie-bladerunner",
      "name": "movie_bladerunner",
      "group": "tf-2606",
      "badge": "모니터링",
      "roas": 503,
      "revenueMan": 887,
      "costMan": 176.2,
      "cnt": 184,
      "valuePerCnt": 48207,
      "firstDate": "2026-07-02",
      "lastDate": "2026-07-09",
      "days": 8,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 83 },
        { "name": "TikTok", "cls": "tt", "pct": 17 }
      ]
    },
    {
      "id": "tf-movie-minor",
      "name": "movie_minor",
      "group": "tf-2606",
      "badge": "양호",
      "roas": 701,
      "revenueMan": 421,
      "costMan": 60.1,
      "cnt": 66,
      "valuePerCnt": 63788,
      "firstDate": "2026-07-02",
      "lastDate": "2026-07-09",
      "days": 8,
      "media": [
        { "name": "Facebook", "cls": "fb", "pct": 80 },
        { "name": "TikTok", "cls": "tt", "pct": 20 }
      ]
    }
  ]
};
