// auto-generated by SEO refresh agent
// last_updated: 2026-07-16

const SEO_DATA = {
  "meta": {
    "lastUpdated": "2026-07-16",
    "period7d": "2026-07-09 ~ 2026-07-16",
    "period28d": "2026-06-18 ~ 2026-07-16",
    "yesterdayDate": "2026-07-13",
    "totalBlogPages": 10
  },
  "performance": {
    "summary": {
      "totalImpressions": 9404,
      "totalClicks": 406,
      "avgPosition": 5.4,
      "avgCTR": 3.6
    },
    "summaryRolling7d": {
      "totalImpressions": 31588,
      "totalClicks": 1341,
      "avgPosition": 5.1,
      "avgCTR": 4.7
    },
    "dailyHistory": [
      {
        "date": "2026-07-07",
        "impressions": 9491,
        "clicks": 397,
        "position": 5.8,
        "ctr": 4.0
      },
      {
        "date": "2026-07-08",
        "impressions": 8357,
        "clicks": 306,
        "position": 5.5,
        "ctr": 3.4
      },
      {
        "date": "2026-07-09",
        "impressions": 8331,
        "clicks": 329,
        "position": 6.4,
        "ctr": 2.9
      },
      {
        "date": "2026-07-10",
        "impressions": 9954,
        "clicks": 349,
        "position": 5.8,
        "ctr": 2.9
      },
      {
        "date": "2026-07-11",
        "impressions": 9344,
        "clicks": 364,
        "position": 5.9,
        "ctr": 3.5
      },
      {
        "date": "2026-07-12",
        "impressions": 9610,
        "clicks": 383,
        "position": 5.7,
        "ctr": 3.2
      },
      {
        "date": "2026-07-13",
        "impressions": 9404,
        "clicks": 406,
        "position": 5.4,
        "ctr": 3.6
      }
    ],
    "pages": [
      {
        "url": "https://www.socar.kr/blog/socar-fee-guide",
        "slug": "socar-fee-guide",
        "position": 3.3,
        "impressions": 9649,
        "clicks": 339,
        "ctr": 3.5,
        "queries": [
          "쏘카",
          "쏘카 이용요금",
          "쏘카 가격",
          "쏘카 1박 2일 비용",
          "쏘카 비용"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-2daysdriving",
        "slug": "socar-tip-2daysdriving",
        "position": 4.0,
        "impressions": 6396,
        "clicks": 302,
        "ctr": 4.7,
        "queries": [
          "쏘카 이용요금",
          "쏘카 가격",
          "쏘카 1박 2일 비용",
          "쏘카 비용",
          "1박2일 렌트카 비용"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tesla-fsd",
        "slug": "socar-tesla-fsd",
        "position": 8.0,
        "impressions": 4041,
        "clicks": 149,
        "ctr": 3.7,
        "queries": [
          "fsd",
          "테슬라 fsd",
          "쏘카 테슬라",
          "fsd 테슬라",
          "쏘카 fsd"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-daejeon-bread-tour",
        "slug": "socar-travel-daejeon-bread-tour",
        "position": 8.7,
        "impressions": 2019,
        "clicks": 35,
        "ctr": 1.7,
        "queries": [
          "성심당",
          "대전 성심당",
          "대전 빵투어",
          "대전 빵집",
          "빵"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-driving-fee-complete-guide",
        "slug": "socar-driving-fee-complete-guide",
        "position": 4.2,
        "impressions": 1970,
        "clicks": 108,
        "ctr": 5.5,
        "queries": [
          "쏘카 주유",
          "쏘카 기름값",
          "쏘카 주행요금",
          "쏘카 주행요금 계산기",
          "쏘카 주유비"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-maydrive",
        "slug": "socar-travel-maydrive",
        "position": 5.6,
        "impressions": 1766,
        "clicks": 42,
        "ctr": 2.4,
        "queries": [
          "서울 드라이브 코스",
          "드라이브 코스",
          "드라이브 추천",
          "서울 근교 당일 드라이브",
          "당일 치기 드라이브 코스"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-2026summer-campaign",
        "slug": "socar-tip-2026summer-campaign",
        "position": 4.7,
        "impressions": 1607,
        "clicks": 48,
        "ctr": 3.0,
        "queries": [
          "쏘카 쿠폰",
          "쏘카 프로모션 코드 2026",
          "쏘카 24시간 무료 쿠폰",
          "쏘카 할인",
          "쏘카 할인쿠폰"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-insurance-guide",
        "slug": "socar-insurance-guide",
        "position": 3.2,
        "impressions": 1507,
        "clicks": 138,
        "ctr": 9.2,
        "queries": [
          "쏘카 보험",
          "쏘카 사고",
          "쏘카 완전보장",
          "쏘카 휴차료",
          "쏘카 실속보장"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-jeju-rentacar",
        "slug": "socar-travel-jeju-rentacar",
        "position": 5.0,
        "impressions": 1320,
        "clicks": 81,
        "ctr": 6.1,
        "queries": [
          "제주도 쏘카 vs 렌트카 디시",
          "제주도 쏘카",
          "제주도 쏘카 vs 렌트카",
          "제주도 쏘카 디시",
          "제주 쏘카 디시"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-beginner-complete-guide",
        "slug": "socar-tip-beginner-complete-guide",
        "position": 4.3,
        "impressions": 1313,
        "clicks": 99,
        "ctr": 7.5,
        "queries": [
          "쏘카 나이",
          "쏘카 운전연습",
          "쏘카 운전연수",
          "쏘카 초보운전",
          "쏘카 운전 교육용 차량 없어짐"
        ]
      }
    ],
    "pagesRolling7d": [
      {
        "url": "https://www.socar.kr/blog/socar-fee-guide",
        "slug": "socar-fee-guide",
        "position": 3.3,
        "impressions": 9649,
        "clicks": 339,
        "ctr": 3.5,
        "queries": [
          "쏘카",
          "쏘카 이용요금",
          "쏘카 가격",
          "쏘카 1박 2일 비용",
          "쏘카 비용"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-2daysdriving",
        "slug": "socar-tip-2daysdriving",
        "position": 4.0,
        "impressions": 6396,
        "clicks": 302,
        "ctr": 4.7,
        "queries": [
          "쏘카 이용요금",
          "쏘카 가격",
          "쏘카 1박 2일 비용",
          "쏘카 비용",
          "1박2일 렌트카 비용"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tesla-fsd",
        "slug": "socar-tesla-fsd",
        "position": 8.0,
        "impressions": 4041,
        "clicks": 149,
        "ctr": 3.7,
        "queries": [
          "fsd",
          "테슬라 fsd",
          "쏘카 테슬라",
          "fsd 테슬라",
          "쏘카 fsd"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-daejeon-bread-tour",
        "slug": "socar-travel-daejeon-bread-tour",
        "position": 8.7,
        "impressions": 2019,
        "clicks": 35,
        "ctr": 1.7,
        "queries": [
          "성심당",
          "대전 성심당",
          "대전 빵투어",
          "대전 빵집",
          "빵"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-driving-fee-complete-guide",
        "slug": "socar-driving-fee-complete-guide",
        "position": 4.2,
        "impressions": 1970,
        "clicks": 108,
        "ctr": 5.5,
        "queries": [
          "쏘카 주유",
          "쏘카 기름값",
          "쏘카 주행요금",
          "쏘카 주행요금 계산기",
          "쏘카 주유비"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-maydrive",
        "slug": "socar-travel-maydrive",
        "position": 5.6,
        "impressions": 1766,
        "clicks": 42,
        "ctr": 2.4,
        "queries": [
          "서울 드라이브 코스",
          "드라이브 코스",
          "드라이브 추천",
          "서울 근교 당일 드라이브",
          "당일 치기 드라이브 코스"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-2026summer-campaign",
        "slug": "socar-tip-2026summer-campaign",
        "position": 4.7,
        "impressions": 1607,
        "clicks": 48,
        "ctr": 3.0,
        "queries": [
          "쏘카 쿠폰",
          "쏘카 프로모션 코드 2026",
          "쏘카 24시간 무료 쿠폰",
          "쏘카 할인",
          "쏘카 할인쿠폰"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-insurance-guide",
        "slug": "socar-insurance-guide",
        "position": 3.2,
        "impressions": 1507,
        "clicks": 138,
        "ctr": 9.2,
        "queries": [
          "쏘카 보험",
          "쏘카 사고",
          "쏘카 완전보장",
          "쏘카 휴차료",
          "쏘카 실속보장"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-jeju-rentacar",
        "slug": "socar-travel-jeju-rentacar",
        "position": 5.0,
        "impressions": 1320,
        "clicks": 81,
        "ctr": 6.1,
        "queries": [
          "제주도 쏘카 vs 렌트카 디시",
          "제주도 쏘카",
          "제주도 쏘카 vs 렌트카",
          "제주도 쏘카 디시",
          "제주 쏘카 디시"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-beginner-complete-guide",
        "slug": "socar-tip-beginner-complete-guide",
        "position": 4.3,
        "impressions": 1313,
        "clicks": 99,
        "ctr": 7.5,
        "queries": [
          "쏘카 나이",
          "쏘카 운전연습",
          "쏘카 운전연수",
          "쏘카 초보운전",
          "쏘카 운전 교육용 차량 없어짐"
        ]
      }
    ],
    "pagesYesterday": [
      {
        "url": "https://www.socar.kr/blog/socar-fee-guide",
        "slug": "socar-fee-guide",
        "position": 3.0,
        "impressions": 2022,
        "clicks": 68,
        "ctr": 3.4
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-2daysdriving",
        "slug": "socar-tip-2daysdriving",
        "position": 3.8,
        "impressions": 1338,
        "clicks": 71,
        "ctr": 5.3
      },
      {
        "url": "https://www.socar.kr/blog/socar-tesla-fsd",
        "slug": "socar-tesla-fsd",
        "position": 7.9,
        "impressions": 730,
        "clicks": 32,
        "ctr": 4.4
      },
      {
        "url": "https://www.socar.kr/blog/socar-driving-fee-complete-guide",
        "slug": "socar-driving-fee-complete-guide",
        "position": 4.2,
        "impressions": 408,
        "clicks": 22,
        "ctr": 5.4
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-2026summer-campaign",
        "slug": "socar-tip-2026summer-campaign",
        "position": 4.8,
        "impressions": 353,
        "clicks": 9,
        "ctr": 2.5
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-jeju-rentacar",
        "slug": "socar-travel-jeju-rentacar",
        "position": 5.0,
        "impressions": 324,
        "clicks": 20,
        "ctr": 6.2
      },
      {
        "url": "https://www.socar.kr/blog/socar-insurance-guide",
        "slug": "socar-insurance-guide",
        "position": 3.3,
        "impressions": 312,
        "clicks": 28,
        "ctr": 9.0
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-beginner-complete-guide",
        "slug": "socar-tip-beginner-complete-guide",
        "position": 4.5,
        "impressions": 298,
        "clicks": 19,
        "ctr": 6.4
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-maydrive",
        "slug": "socar-travel-maydrive",
        "position": 6.1,
        "impressions": 278,
        "clicks": 10,
        "ctr": 3.6
      },
      {
        "url": "https://www.socar.kr/blog/ev-beginner-4-tips",
        "slug": "ev-beginner-4-tips",
        "position": 4.1,
        "impressions": 222,
        "clicks": 14,
        "ctr": 6.3
      }
    ],
    "history": [
      {
        "week": "2026-07-05",
        "totalImpressions": 28916,
        "totalClicks": 1189
      },
      {
        "week": "2026-07-06",
        "totalImpressions": 29617,
        "totalClicks": 1221
      },
      {
        "week": "2026-07-07",
        "totalImpressions": 29771,
        "totalClicks": 1162
      },
      {
        "week": "2026-07-08",
        "totalImpressions": 30053,
        "totalClicks": 1143
      },
      {
        "week": "2026-07-09",
        "totalImpressions": 31161,
        "totalClicks": 1198
      },
      {
        "week": "2026-07-10",
        "totalImpressions": 31341,
        "totalClicks": 1199
      },
      {
        "week": "2026-07-11",
        "totalImpressions": 30629,
        "totalClicks": 1181
      },
      {
        "week": "2026-07-12",
        "totalImpressions": 30275,
        "totalClicks": 1259
      },
      {
        "week": "2026-07-13",
        "totalImpressions": 30917,
        "totalClicks": 1274
      },
      {
        "week": "2026-07-14",
        "totalImpressions": 30264,
        "totalClicks": 1169
      },
      {
        "week": "2026-07-15",
        "totalImpressions": 30680,
        "totalClicks": 1269
      },
      {
        "week": "2026-07-16",
        "totalImpressions": 31588,
        "totalClicks": 1341
      }
    ]
  },
  "refresh": [],
  "topics_brand": [
    {
      "title": "쏘카 처음 이용자를 위한 완벽 가이드: 예약부터 반납까지",
      "slug_suggestion": "socar-first-time-user-guide",
      "queries": [
        "쏘카 이용 방법",
        "쏘카 이용방법",
        "쏘카 반납"
      ],
      "total_impressions": 1760,
      "seasonal_index": 1.36,
      "is_trending": true,
      "rationale": "초보 이용자들의 궁금증을 해소하고 서비스 진입 장벽을 낮출 수 있는 핵심 주제"
    },
    {
      "title": "쏘카 요금 완벽 분석: 렌트비부터 보험까지 알뜰하게 이용하는 방법",
      "slug_suggestion": "socar-cost-analysis-guide",
      "queries": [
        "쏘카 렌트비",
        "쏘카 보험",
        "쏘카 이용 요금",
        "쏘카 이용요금"
      ],
      "total_impressions": 1960,
      "seasonal_index": 1.31,
      "is_trending": true,
      "rationale": "비용에 민감한 사용자들을 위한 실용적인 정보 제공"
    },
    {
      "title": "쏘카 핸들러의 모든 것: 역할, 혜택, 지원 방법",
      "slug_suggestion": "socar-handler-guide",
      "queries": [
        "쏘카 핸들러",
        "쏘카 채용"
      ],
      "total_impressions": 2180,
      "seasonal_index": 1.48,
      "is_trending": true,
      "rationale": "쏘카 핸들러에 대한 높은 관심도를 반영한 정보성 콘텐츠"
    },
    {
      "title": "쏘카로 즐기는 완벽한 1박 2일 여행: 비용 절약 팁",
      "slug_suggestion": "socar-overnight-trip-guide",
      "queries": [
        "쏘카 1 박 2 일 비용",
        "쏘카 렌트"
      ],
      "total_impressions": 1470,
      "seasonal_index": 0.99,
      "is_trending": false,
      "rationale": "단기 여행객을 위한 실용적인 카셰어링 활용 가이드"
    },
    {
      "title": "쏘카 하이패스 사용법: 톨게이트 빠르게 통과하는 팁",
      "slug_suggestion": "socar-hi-pass-usage-guide",
      "queries": [
        "쏘카 하이 패스",
        "쏘카 하이패스"
      ],
      "total_impressions": 960,
      "seasonal_index": 1.22,
      "is_trending": true,
      "rationale": "장거리 운전자를 위한 유용한 기능 활용 팁"
    },
    {
      "title": "쏘카 쿠폰 활용 극대화: 할인받는 방법 총정리",
      "slug_suggestion": "socar-coupon-maximization-guide",
      "queries": [
        "쏘카 쿠폰",
        "쏘카 모바일 상품권"
      ],
      "total_impressions": 800,
      "seasonal_index": 1.08,
      "is_trending": true,
      "rationale": "비용 절감을 원하는 사용자들을 위한 실용적인 정보"
    },
    {
      "title": "쏘카 테슬라 이용 가이드: 전기차 초보자를 위한 팁",
      "slug_suggestion": "socar-tesla-usage-guide",
      "queries": [
        "쏘카 테슬라"
      ],
      "total_impressions": 320,
      "seasonal_index": 1.48,
      "is_trending": true,
      "rationale": "친환경 전기차에 대한 관심 증가와 실용적인 이용 정보 제공"
    },
    {
      "title": "쏘카 장기렌트 vs 일반 장기렌트: 어떤 게 더 유리할까?",
      "slug_suggestion": "socar-long-term-rental-comparison",
      "queries": [
        "쏘카 장기 렌트"
      ],
      "total_impressions": 320,
      "seasonal_index": 1.15,
      "is_trending": false,
      "rationale": "장기적인 차량 이용을 고민하는 사용자들을 위한 비교 분석"
    },
    {
      "title": "쏘카 고객센터 100% 활용법: 문제 해결부터 문의까지",
      "slug_suggestion": "socar-customer-service-guide",
      "queries": [
        "쏘카 고객센터",
        "쏘카 고객 센터",
        "쏘카 고객센터 전화번호"
      ],
      "total_impressions": 1660,
      "seasonal_index": 0.85,
      "is_trending": false,
      "rationale": "서비스 이용 중 발생할 수 있는 문제에 대한 해결책 제시"
    }
  ],
  "topics_category": [
    {
      "title": "제주 여름 숨은 명소, 쏘카로 쉽게 가는 인생 사진 맛집 5선",
      "slug_suggestion": "jeju-summer-hidden-spots-photo",
      "queries": [
        "제주 여행",
        "제주도 여행",
        "제주 명소"
      ],
      "total_impressions": 320000,
      "seasonal_index": 1.4,
      "is_trending": true,
      "rationale": "여름 휴가철 제주 여행 수요 급증, 인스타그램 인생샷 트렌드와 연계"
    },
    {
      "title": "부산 해운대 근처 쏘카존 총정리! 주차 걱정 없는 여름 바다 여행",
      "slug_suggestion": "busan-haeundae-socar-zone-guide",
      "queries": [
        "부산 여행",
        "해운대 주차",
        "부산 가볼만한곳"
      ],
      "total_impressions": 180000,
      "seasonal_index": 1.5,
      "is_trending": true,
      "rationale": "여름 휴가 성수기 부산 여행 수요 증가, 주차 문제 해결책 제시"
    },
    {
      "title": "강원도 여름 계곡 드라이브 코스, 쏘카로 시원하게 떠나요",
      "slug_suggestion": "gangwon-summer-valley-drive-course",
      "queries": [
        "강원도 여행",
        "여름 계곡",
        "드라이브 코스"
      ],
      "total_impressions": 150000,
      "seasonal_index": 1.3,
      "is_trending": true,
      "rationale": "무더위 피서 수요 증가, 강원도 계곡 여행 인기"
    },
    {
      "title": "경주 야간 투어 완벽 가이드, 쏘카로 즐기는 야경 명소 Best 5",
      "slug_suggestion": "gyeongju-night-tour-guide",
      "queries": [
        "경주 여행",
        "경주 야경",
        "경주 가볼만한곳"
      ],
      "total_impressions": 100000,
      "seasonal_index": 1.2,
      "is_trending": true,
      "rationale": "여름 휴가철 경주 여행 수요 증가, 야간 관광 트렌드 반영"
    },
    {
      "title": "전주 한옥마을 근처 쏘카존 꿀팁! 주차 걱정 없는 맛집 투어",
      "slug_suggestion": "jeonju-hanok-village-socar-zone-food-tour",
      "queries": [
        "전주 여행",
        "전주 한옥마을",
        "전주 맛집"
      ],
      "total_impressions": 130000,
      "seasonal_index": 1.1,
      "is_trending": false,
      "rationale": "여름 휴가 분산 효과로 전주 여행 수요 증가, 주차 문제 해결책 제시"
    },
    {
      "title": "서울 근교 1박2일 드라이브 코스, 쏘카로 떠나는 여름 힐링 여행",
      "slug_suggestion": "seoul-nearby-2days-drive-course",
      "queries": [
        "서울 근교 여행",
        "주말 여행",
        "드라이브 코스"
      ],
      "total_impressions": 200000,
      "seasonal_index": 1.2,
      "is_trending": true,
      "rationale": "여름 휴가철 근거리 여행 수요 증가, 주말 여행 트렌드 반영"
    },
    {
      "title": "여름 차박 캠핑 꿀팁! 쏘카 SUV로 떠나는 시원한 숲속 여행",
      "slug_suggestion": "summer-car-camping-tips-suv",
      "queries": [
        "차박",
        "캠핑",
        "여름 캠핑"
      ],
      "total_impressions": 180000,
      "seasonal_index": 1.4,
      "is_trending": true,
      "rationale": "여름 캠핑 수요 급증, SUV 차박 트렌드와 연계"
    },
    {
      "title": "쏘카 전기차로 떠나는 친환경 제주 여행, 충전소 위치부터 주의사항까지!",
      "slug_suggestion": "jeju-eco-friendly-travel-electric-car",
      "queries": [
        "제주 전기차",
        "전기차 여행",
        "제주도 여행"
      ],
      "total_impressions": 80000,
      "seasonal_index": 1.3,
      "is_trending": true,
      "rationale": "여름 휴가철 제주 여행 수요와 친환경 여행 트렌드 결합"
    },
    {
      "title": "쏘카로 즐기는 여름 당일치기 드라이브 코스 Best 5",
      "slug_suggestion": "summer-one-day-drive-course-top5",
      "queries": [
        "당일치기 여행",
        "드라이브 코스",
        "여름 여행"
      ],
      "total_impressions": 150000,
      "seasonal_index": 1.2,
      "is_trending": true,
      "rationale": "여름 휴가철 단기 여행 수요 증가, 당일치기 드라이브 트렌드 반영"
    }
  ],
  "authors": {
    "authors": [
      {
        "name": "anderson",
        "totalPosts": 11,
        "totalImpressions": 18424,
        "totalClicks": 770,
        "avgPosition": 5.0,
        "avgCTR": 4.1,
        "dailyHistory": [
          {
            "date": "2026-07-07",
            "impressions": 2754,
            "clicks": 127
          },
          {
            "date": "2026-07-08",
            "impressions": 2465,
            "clicks": 96
          },
          {
            "date": "2026-07-09",
            "impressions": 2391,
            "clicks": 95
          },
          {
            "date": "2026-07-10",
            "impressions": 2707,
            "clicks": 108
          },
          {
            "date": "2026-07-11",
            "impressions": 2474,
            "clicks": 100
          },
          {
            "date": "2026-07-12",
            "impressions": 2875,
            "clicks": 119
          },
          {
            "date": "2026-07-13",
            "impressions": 2758,
            "clicks": 125
          }
        ],
        "pages": [
          {
            "url": "https://www.socar.kr/blog/socar-tip-2daysdriving",
            "slug": "socar-tip-2daysdriving",
            "impressions": 13110,
            "clicks": 591,
            "position": 3.9,
            "ctr": 4.5
          },
          {
            "url": "https://www.socar.kr/blog/socar-tip-2026summer-campaign",
            "slug": "socar-tip-2026summer-campaign",
            "impressions": 3706,
            "clicks": 130,
            "position": 4.7,
            "ctr": 3.5
          },
          {
            "url": "https://www.socar.kr/blog/socar-travel-maydrive",
            "slug": "socar-travel-maydrive",
            "impressions": 3437,
            "clicks": 59,
            "position": 5.7,
            "ctr": 1.7
          },
          {
            "url": "https://www.socar.kr/blog/socar-travel-jeju-rentacar",
            "slug": "socar-travel-jeju-rentacar",
            "impressions": 2738,
            "clicks": 148,
            "position": 4.8,
            "ctr": 5.6
          },
          {
            "url": "https://www.socar.kr/blog/socar-tip-rentacar-guide",
            "slug": "socar-tip-rentacar-guide",
            "impressions": 2003,
            "clicks": 45,
            "position": 5.2,
            "ctr": 2.2
          },
          {
            "url": "https://www.socar.kr/blog/socar-tip-service-comparison",
            "slug": "socar-tip-service-comparison",
            "impressions": 1545,
            "clicks": 33,
            "position": 5.3,
            "ctr": 2.0
          },
          {
            "url": "https://www.socar.kr/blog/socar-travel-camper",
            "slug": "socar-travel-camper",
            "impressions": 405,
            "clicks": 53,
            "position": 4.1,
            "ctr": 12.5
          },
          {
            "url": "https://www.socar.kr/blog/socar-tip-premium-car",
            "slug": "socar-tip-premium-car",
            "impressions": 397,
            "clicks": 47,
            "position": 4.2,
            "ctr": 11.8
          },
          {
            "url": "https://www.socar.kr/blog/socar-travel-beach",
            "slug": "socar-travel-beach",
            "impressions": 254,
            "clicks": 2,
            "position": 6.3,
            "ctr": 0.9
          },
          {
            "url": "https://www.socar.kr/blog/socar-travel-temple-drive",
            "slug": "socar-travel-temple-drive",
            "impressions": 46,
            "clicks": 0,
            "position": 7.6,
            "ctr": 0.0
          },
          {
            "url": "https://www.socar.kr/blog/socar-tip-insuranceguide",
            "slug": "socar-tip-insuranceguide",
            "impressions": 4,
            "clicks": 0,
            "position": 3.3,
            "ctr": 0.0
          }
        ]
      },
      {
        "name": "win",
        "totalPosts": 3,
        "totalImpressions": 2409,
        "totalClicks": 152,
        "avgPosition": 5.5,
        "avgCTR": 4.2,
        "dailyHistory": [
          {
            "date": "2026-07-07",
            "impressions": 295,
            "clicks": 21
          },
          {
            "date": "2026-07-08",
            "impressions": 280,
            "clicks": 21
          },
          {
            "date": "2026-07-09",
            "impressions": 289,
            "clicks": 13
          },
          {
            "date": "2026-07-10",
            "impressions": 354,
            "clicks": 28
          },
          {
            "date": "2026-07-11",
            "impressions": 383,
            "clicks": 25
          },
          {
            "date": "2026-07-12",
            "impressions": 390,
            "clicks": 21
          },
          {
            "date": "2026-07-13",
            "impressions": 418,
            "clicks": 23
          }
        ],
        "pages": [
          {
            "url": "https://www.socar.kr/blog/socar-tip-beginner-complete-guide",
            "slug": "socar-tip-beginner-complete-guide",
            "impressions": 2421,
            "clicks": 196,
            "position": 4.4,
            "ctr": 8.1
          },
          {
            "url": "https://www.socar.kr/blog/socar-travel-summer-mountain-trekking",
            "slug": "socar-travel-summer-mountain-trekking",
            "impressions": 531,
            "clicks": 20,
            "position": 6.1,
            "ctr": 3.8
          },
          {
            "url": "https://www.socar.kr/blog/socar-travel-pohang-mart-attack-course",
            "slug": "socar-travel-pohang-mart-attack-course",
            "impressions": 447,
            "clicks": 3,
            "position": 6.1,
            "ctr": 0.7
          }
        ]
      },
      {
        "name": "sanghi",
        "totalPosts": 6,
        "totalImpressions": 2677,
        "totalClicks": 53,
        "avgPosition": 5.7,
        "avgCTR": 3.0,
        "dailyHistory": [
          {
            "date": "2026-07-07",
            "impressions": 424,
            "clicks": 10
          },
          {
            "date": "2026-07-08",
            "impressions": 378,
            "clicks": 7
          },
          {
            "date": "2026-07-09",
            "impressions": 401,
            "clicks": 4
          },
          {
            "date": "2026-07-10",
            "impressions": 369,
            "clicks": 4
          },
          {
            "date": "2026-07-11",
            "impressions": 294,
            "clicks": 4
          },
          {
            "date": "2026-07-12",
            "impressions": 435,
            "clicks": 8
          },
          {
            "date": "2026-07-13",
            "impressions": 376,
            "clicks": 16
          }
        ],
        "pages": [
          {
            "url": "https://www.socar.kr/blog/socar-travel-domestic-blacklabel",
            "slug": "socar-travel-domestic-blacklabel",
            "impressions": 1691,
            "clicks": 32,
            "position": 6.3,
            "ctr": 1.9
          },
          {
            "url": "https://www.socar.kr/blog/socar-travel-jeju-car",
            "slug": "socar-travel-jeju-car",
            "impressions": 673,
            "clicks": 8,
            "position": 4.5,
            "ctr": 1.2
          },
          {
            "url": "https://www.socar.kr/blog/socar-tip-blacklabel-wedding-car",
            "slug": "socar-tip-blacklabel-wedding-car",
            "impressions": 611,
            "clicks": 18,
            "position": 5.3,
            "ctr": 3.2
          },
          {
            "url": "https://www.socar.kr/blog/socar-tip-golf-blacklabel",
            "slug": "socar-tip-golf-blacklabel",
            "impressions": 464,
            "clicks": 6,
            "position": 5.9,
            "ctr": 1.2
          },
          {
            "url": "https://www.socar.kr/blog/socar-tip-blacklabel-care",
            "slug": "socar-tip-blacklabel-care",
            "impressions": 209,
            "clicks": 12,
            "position": 5.8,
            "ctr": 5.9
          },
          {
            "url": "https://www.socar.kr/blog/socar-travel-jeju-rental-car-black-label",
            "slug": "socar-travel-jeju-rental-car-black-label",
            "impressions": 139,
            "clicks": 8,
            "position": 6.6,
            "ctr": 4.6
          }
        ]
      },
      {
        "name": "호도",
        "totalPosts": 2,
        "totalImpressions": 732,
        "totalClicks": 0,
        "avgPosition": 6.7,
        "avgCTR": 0.4,
        "dailyHistory": [
          {
            "date": "2026-07-07",
            "impressions": 108,
            "clicks": 0
          },
          {
            "date": "2026-07-08",
            "impressions": 138,
            "clicks": 0
          },
          {
            "date": "2026-07-09",
            "impressions": 114,
            "clicks": 0
          },
          {
            "date": "2026-07-10",
            "impressions": 71,
            "clicks": 0
          },
          {
            "date": "2026-07-11",
            "impressions": 89,
            "clicks": 0
          },
          {
            "date": "2026-07-12",
            "impressions": 103,
            "clicks": 0
          },
          {
            "date": "2026-07-13",
            "impressions": 109,
            "clicks": 0
          }
        ],
        "pages": [
          {
            "url": "https://www.socar.kr/blog/rainy-season-driving-guide-2026",
            "slug": "rainy-season-driving-guide-2026",
            "impressions": 1745,
            "clicks": 3,
            "position": 6.7,
            "ctr": 0.4
          }
        ]
      },
      {
        "name": "olive",
        "totalPosts": 2,
        "totalImpressions": 1606,
        "totalClicks": 38,
        "avgPosition": 5.3,
        "avgCTR": 2.8,
        "dailyHistory": [
          {
            "date": "2026-07-07",
            "impressions": 245,
            "clicks": 6
          },
          {
            "date": "2026-07-08",
            "impressions": 199,
            "clicks": 4
          },
          {
            "date": "2026-07-09",
            "impressions": 206,
            "clicks": 6
          },
          {
            "date": "2026-07-10",
            "impressions": 272,
            "clicks": 6
          },
          {
            "date": "2026-07-11",
            "impressions": 226,
            "clicks": 7
          },
          {
            "date": "2026-07-12",
            "impressions": 235,
            "clicks": 7
          },
          {
            "date": "2026-07-13",
            "impressions": 223,
            "clicks": 2
          }
        ],
        "pages": [
          {
            "url": "https://www.socar.kr/blog/socar-travel-busan-beach-blacklabel-2026",
            "slug": "socar-travel-busan-beach-blacklabel-2026",
            "impressions": 1667,
            "clicks": 24,
            "position": 6.2,
            "ctr": 1.4
          },
          {
            "url": "https://www.socar.kr/blog/socar-tips-busan-carseat-blacklabel",
            "slug": "socar-tips-busan-carseat-blacklabel",
            "impressions": 676,
            "clicks": 27,
            "position": 4.4,
            "ctr": 4.2
          }
        ]
      },
      {
        "name": "didi",
        "totalPosts": 1,
        "totalImpressions": 711,
        "totalClicks": 23,
        "avgPosition": 4.8,
        "avgCTR": 2.7,
        "dailyHistory": [
          {
            "date": "2026-07-07",
            "impressions": 90,
            "clicks": 4
          },
          {
            "date": "2026-07-08",
            "impressions": 151,
            "clicks": 1
          },
          {
            "date": "2026-07-09",
            "impressions": 88,
            "clicks": 3
          },
          {
            "date": "2026-07-10",
            "impressions": 84,
            "clicks": 4
          },
          {
            "date": "2026-07-11",
            "impressions": 80,
            "clicks": 5
          },
          {
            "date": "2026-07-12",
            "impressions": 109,
            "clicks": 4
          },
          {
            "date": "2026-07-13",
            "impressions": 109,
            "clicks": 2
          }
        ],
        "pages": [
          {
            "url": "https://www.socar.kr/blog/socar-tip-transit-hub-oneway",
            "slug": "socar-tip-transit-hub-oneway",
            "impressions": 1027,
            "clicks": 25,
            "position": 4.8,
            "ctr": 2.7
          }
        ]
      }
    ],
    "missingAuthors": []
  }
};