// auto-generated by SEO refresh agent
// last_updated: 2026-05-28

const SEO_DATA = {
  "meta": {
    "lastUpdated": "2026-05-28",
    "period7d": "2026-05-21 ~ 2026-05-28",
    "period28d": "2026-04-30 ~ 2026-05-28",
    "totalBlogPages": 20
  },
  "performance": {
    "summary": {
      "totalImpressions": 18275,
      "totalClicks": 737,
      "avgPosition": 5.4,
      "avgCTR": 4.1
    },
    "pages": [
      {
        "url": "https://www.socar.kr/blog/socar-fee-guide",
        "slug": "socar-fee-guide",
        "position": 4.2,
        "impressions": 4316,
        "clicks": 200,
        "ctr": 4.6,
        "queries": [
          "쏘카 가격",
          "쏘카",
          "쏘카 하루 가격",
          "쏘카 하이패스",
          "쏘카 비용"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-2daysdriving",
        "slug": "socar-tip-2daysdriving",
        "position": 4.4,
        "impressions": 4194,
        "clicks": 140,
        "ctr": 3.3,
        "queries": [
          "쏘카 가격",
          "쏘카 하루 가격",
          "쏘카 비용",
          "쏘카 이용요금",
          "쏘카 렌트"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tesla-fsd",
        "slug": "socar-tesla-fsd",
        "position": 6.6,
        "impressions": 1446,
        "clicks": 70,
        "ctr": 4.8,
        "queries": [
          "fsd",
          "테슬라 fsd",
          "쏘카 테슬라",
          "쏘카 fsd",
          "감독형 fsd"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-driving-fee-complete-guide",
        "slug": "socar-driving-fee-complete-guide",
        "position": 5.3,
        "impressions": 1276,
        "clicks": 29,
        "ctr": 2.3,
        "queries": [
          "쏘카 주유",
          "쏘카 주행요금",
          "쏘카 기름값",
          "쏘카 기름",
          "쏘카 기름 충전"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-maydrive",
        "slug": "socar-travel-maydrive",
        "position": 5.2,
        "impressions": 1160,
        "clicks": 29,
        "ctr": 2.5,
        "queries": [
          "드라이브 코스",
          "당일 치기 드라이브 코스",
          "5월 당일 치기 여행",
          "드라이브 추천",
          "드라이브"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-rentacar-guide",
        "slug": "socar-tip-rentacar-guide",
        "position": 5.6,
        "impressions": 769,
        "clicks": 12,
        "ctr": 1.6,
        "queries": [
          "쏘카 렌트 조건",
          "쏘카",
          "가이드가 필요한 예약자에게 가장 적합한 렌터카 검색 사이트는 무엇인가요?",
          "쏘카 연령",
          "쏘카 조건"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-jeju-rentacar",
        "slug": "socar-travel-jeju-rentacar",
        "position": 6.3,
        "impressions": 646,
        "clicks": 17,
        "ctr": 2.6,
        "queries": [
          "제주도 쏘카 vs 렌트카",
          "제주도 쏘카 vs 렌트카 디시",
          "쏘카 제주도 요금",
          "쏘카 제주도 렌트",
          "쏘카 제주도"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-insurance-guide",
        "slug": "socar-insurance-guide",
        "position": 3.6,
        "impressions": 632,
        "clicks": 50,
        "ctr": 7.9,
        "queries": [
          "쏘카 보험",
          "쏘카 사고",
          "쏘카 실속보장",
          "쏘카 완전보장",
          "쏘카 표준보장"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-beginner-complete-guide",
        "slug": "socar-tip-beginner-complete-guide",
        "position": 5.0,
        "impressions": 617,
        "clicks": 49,
        "ctr": 7.9,
        "queries": [
          "쏘카 운전연습",
          "쏘카 완전보장",
          "쏘카 초보운전",
          "쏘카 운전 연습용 차량",
          "쏘카 표준보장"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/ev-beginner-4-tips",
        "slug": "ev-beginner-4-tips",
        "position": 3.9,
        "impressions": 516,
        "clicks": 41,
        "ctr": 7.9,
        "queries": [
          "쏘카 전기차 충전",
          "쏘카 전기차",
          "쏘카 전기차 주행요금",
          "쏘카 아이오닉9",
          "쏘카 전기차 충전소"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-9900won-commute-tip",
        "slug": "socar-9900won-commute-tip",
        "position": 5.2,
        "impressions": 442,
        "clicks": 24,
        "ctr": 5.4,
        "queries": [
          "쏘카 쿠폰",
          "쏘카 주행요금 기름값",
          "쏘카 당일최저가",
          "쏘카 9900원",
          "쏘카 30km 초과"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-temple-drive",
        "slug": "socar-travel-temple-drive",
        "position": 5.5,
        "impressions": 373,
        "clicks": 8,
        "ctr": 2.1,
        "queries": [
          "경주 부처님오신날"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-transit-hub-oneway",
        "slug": "socar-tip-transit-hub-oneway",
        "position": 5.6,
        "impressions": 370,
        "clicks": 4,
        "ctr": 1.1,
        "queries": [
          "쏘카 편도",
          "쏘카 편도 비용",
          "쏘카 서울 부산 편도 비용",
          "부산에서 공항 픽업이 포함된 주말 도시 여행에 가장 적합한 렌터카 옵션은 무엇인가요?",
          "부산역 쏘카"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-delivery-complete-guide",
        "slug": "socar-delivery-complete-guide",
        "position": 4.1,
        "impressions": 317,
        "clicks": 27,
        "ctr": 8.5,
        "queries": [
          "쏘카 배달",
          "쏘카 배달 요청사항",
          "쏘카 예약시간보다 일찍",
          "쏘카 예약 시간보다 일찍",
          "차 배달"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-blacklabel-wedding-car",
        "slug": "socar-tip-blacklabel-wedding-car",
        "position": 6.8,
        "impressions": 273,
        "clicks": 9,
        "ctr": 3.3,
        "queries": [
          "웨딩카",
          "쏘카 블랙라벨",
          "쏘카 블랙라벨 후기",
          "웨딩카 대여",
          "쏘카 동승운전자 추가 요금"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-busan-gyeongnam-ulsan-festival-2026",
        "slug": "socar-travel-busan-gyeongnam-ulsan-festival-2026",
        "position": 6.7,
        "impressions": 230,
        "clicks": 3,
        "ctr": 1.3,
        "queries": []
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-jeju-car",
        "slug": "socar-travel-jeju-car",
        "position": 6.0,
        "impressions": 221,
        "clicks": 5,
        "ctr": 2.3,
        "queries": [
          "쏘카 실속보장",
          "쏘카 완전보장",
          "쏘카 완전보장 표준보장",
          "쏘카 표준보장",
          "쏘카 긁으면"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-golf-blacklabel",
        "slug": "socar-tip-golf-blacklabel",
        "position": 5.6,
        "impressions": 168,
        "clicks": 8,
        "ctr": 4.8,
        "queries": [
          "쏘카 카니발",
          "쏘카 블랙라벨",
          "쏘카 블랙라벨 후기",
          "쏘카 톨비",
          "카니발 쏘카"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-black-label-premium-guide",
        "slug": "socar-black-label-premium-guide",
        "position": 6.2,
        "impressions": 164,
        "clicks": 3,
        "ctr": 1.8,
        "queries": [
          "쏘카 블랙라벨",
          "쏘카 외제차",
          "쏘카 모델3",
          "쏘카 블랙라벨 후기",
          "쏘카 제네시스"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-tip-jeju-terminal",
        "slug": "socar-tip-jeju-terminal",
        "position": 5.7,
        "impressions": 145,
        "clicks": 9,
        "ctr": 6.2,
        "queries": [
          "제주 쏘카터미널",
          "쏘카 스마트 키 거리",
          "쏘카 제주",
          "쏘카 카시트",
          "쏘카 카시트 대여"
        ]
      }
    ],
    "history": [
      {
        "week": "2026-05-17",
        "totalImpressions": 16102,
        "totalClicks": 516
      },
      {
        "week": "2026-05-18",
        "totalImpressions": 19729,
        "totalClicks": 642
      },
      {
        "week": "2026-05-19",
        "totalImpressions": 22379,
        "totalClicks": 722
      },
      {
        "week": "2026-05-20",
        "totalImpressions": 23287,
        "totalClicks": 767
      },
      {
        "week": "2026-05-21",
        "totalImpressions": 23731,
        "totalClicks": 821
      },
      {
        "week": "2026-05-22",
        "totalImpressions": 24018,
        "totalClicks": 859
      },
      {
        "week": "2026-05-23",
        "totalImpressions": 23742,
        "totalClicks": 836
      },
      {
        "week": "2026-05-24",
        "totalImpressions": 23553,
        "totalClicks": 868
      },
      {
        "week": "2026-05-25",
        "totalImpressions": 22082,
        "totalClicks": 822
      },
      {
        "week": "2026-05-26",
        "totalImpressions": 20077,
        "totalClicks": 758
      },
      {
        "week": "2026-05-27",
        "totalImpressions": 19234,
        "totalClicks": 721
      },
      {
        "week": "2026-05-28",
        "totalImpressions": 18275,
        "totalClicks": 737
      }
    ]
  },
  "refresh": [
    {
      "url": "https://www.socar.kr/blog/socar-travel-pohang-mart-attack-course",
      "position": 12.0,
      "impressions": 1210,
      "clicks": 8,
      "ctr": 0.7,
      "queries": [
        "제휴문의",
        "죽도",
        "포항 마트",
        "포항 시내",
        "1500*1.5"
      ],
      "analysis": "[T1] 리드문: ✅ \n- 포항 마트어택의 핵심 요소와 장점을 잘 설명하고 있음\n\n[T2] H2 개수: ✅ \n- 6개의 H2 사용, 적절한 수준\n\n[T3] 질문형 H2: ✅\n- 2개의 질문형 H2 사용, 적절함\n\n[T4] 키워드 배치: ⚠️\n- \"포항 마트\", \"포항 시내\" 등 주요 키워드 추가 배치 필요\n- 섹션 제목에 키워드 활용 강화 (예: \"포항 시내 마트어택 코스\")\n\n[T5] 분량: ✅\n- 약 2,000자로 충분한 분량\n\n[T7] 구조: ⚠️\n- 목차나 요약 섹션 추가 권장\n- 각 장소별 핵심 정보(주소, 운영시간 등)를 표로 정리하면 가독성 향상\n\n보강 제안:\n1. 주요 키워드를 H2, H3 제목에 더 적극적으로 활용\n2. 포항 시내 주요 마트 리스트와 간단한 설명 추가\n3. 마트어택 코스를 요약한 인포그래픽 또는 지도 이미지 삽입\n4. \"포항 마트어택 꿀팁\" 등의 실용적인 정보 섹션 추가"
    },
    {
      "url": "https://www.socar.kr/blog/socar-travel-busan-gyeongnam-ulsan-festival-2026",
      "position": 11.4,
      "impressions": 1191,
      "clicks": 11,
      "ctr": 0.9,
      "queries": [
        "봄에 하는 축제",
        "5월 16일 축제",
        "026969",
        "2026년 5월 경남 축제 일정",
        "2026년 5월 축제"
      ],
      "analysis": "[T1] 리드문: ✅ \n- 적절한 리드문이 있습니다.\n\n[T2] H2 개수: ✅\n- 5개의 H2가 사용되어 적절합니다.\n\n[T3] 질문형 H2: ⚠️ \n- 질문형 H2를 추가하면 좋습니다. 예: \"부산·경남·울산 봄 축제, 어떻게 즐기면 좋을까요?\"\n\n[T4] 키워드 배치: ⚠️\n- 주요 키워드인 \"봄 축제\", \"2026년 5월 축제\" 등을 더 자주 사용하면 좋습니다.\n\n[T5] 분량: ✅\n- 충분한 분량의 콘텐츠가 있습니다.\n\n[T7] 구조: ⚠️\n- 각 축제별로 \"교통 정보\" 섹션을 추가하면 유용할 것 같습니다.\n- 마지막에 \"축제 준비 팁\" 섹션을 추가하여 실용적인 정보를 제공하면 좋겠습니다."
    },
    {
      "url": "https://www.socar.kr/blog/socar-travel-jeju-rental-car-black-label",
      "position": 11.0,
      "impressions": 308,
      "clicks": 5,
      "ctr": 1.6,
      "queries": [
        "car rental",
        "jeju car rental",
        "the black label",
        "가족 여행 비교",
        "라미리"
      ],
      "analysis": "[T1] 리드문: ✅\n- 현재 리드문이 잘 구성되어 있습니다. 주요 키워드와 콘텐츠 내용을 잘 요약하고 있습니다.\n\n[T2] H2 개수: ✅ \n- 4개의 H2 제목이 사용되어 적절한 구조를 갖추고 있습니다.\n\n[T3] 질문형 H2: ✅\n- 3개의 H2가 질문 형식으로 되어 있어 적절합니다.\n\n[T4] 키워드 배치: ⚠️\n- \"제주 렌트카\", \"제주 여행\" 키워드를 더 자주 사용할 수 있습니다.\n- \"차량 컨디션\" 키워드도 추가로 사용하면 좋겠습니다.\n\n[T5] 분량: ✅\n- 충분한 분량으로 작성되어 있습니다.\n\n[T7] 구조: ✅\n- 전체적인 구조가 잘 짜여 있습니다. 소제목, 리스트, 이미지 등을 적절히 활용하고 있습니다.\n\n보강 제안:\n1. \"제주 렌트카\"와 \"제주 여행\" 키워드를 본문에 더 자주 사용하세요.\n2. \"차량 컨디션\"에 대한 내용을 좀 더 강조하고 관련 키워드 사용을 늘리세요.\n3. FAQ 섹션을 추가하여 주요 키워드를 포함한 질문과 답변을 제공하면 SEO에 도움이 될 것입니다.\n4. 메타 디스크립션을 최적화하여 주요 키워드를 포함시키세요."
    }
  ],
  "topics_brand": [
    {
      "title": "쏘카 이용 요금 완벽 가이드: 1박2일부터 장기렌트까지",
      "slug_suggestion": "socar-pricing-guide",
      "queries": [
        "쏘카 이용 요금",
        "쏘카 1박2일 비용",
        "쏘카 장기 렌트"
      ],
      "total_impressions": 1520,
      "seasonal_index": 1.17,
      "is_trending": true,
      "rationale": "이용 요금에 대한 상세 정보를 제공하여 사용자의 비용 관련 궁금증 해소"
    },
    {
      "title": "쏘카 핸들러의 모든 것: 역할부터 지원 방법까지",
      "slug_suggestion": "socar-handler-guide",
      "queries": [
        "쏘카 핸들러",
        "쏘카 핸들러 디시",
        "쏘카 채용"
      ],
      "total_impressions": 2500,
      "seasonal_index": 1.28,
      "is_trending": true,
      "rationale": "쏘카 핸들러에 대한 관심이 높아 관련 정보 제공 필요"
    },
    {
      "title": "쏘카로 즐기는 제주도 여행: 현지 이용 팁 총정리",
      "slug_suggestion": "socar-jeju-travel-tips",
      "queries": [
        "제주도 쏘카",
        "쏘카 제주",
        "쏘카 제주도"
      ],
      "total_impressions": 1370,
      "seasonal_index": 0.89,
      "is_trending": false,
      "rationale": "제주도 여행 시즌에 맞춰 쏘카 이용 팁 제공"
    },
    {
      "title": "쏘카 플랜 & 패스포트 비교 분석: 어떤 게 더 이득일까?",
      "slug_suggestion": "socar-plan-passport-comparison",
      "queries": [
        "쏘카 플랜",
        "쏘카 패스포트",
        "쏘카 이용 요금"
      ],
      "total_impressions": 1120,
      "seasonal_index": 1.19,
      "is_trending": false,
      "rationale": "다양한 이용 방식에 대한 비교 분석으로 사용자 의사결정 지원"
    },
    {
      "title": "쏘카 하이패스 & 보험 가이드: 알아두면 유용한 팁",
      "slug_suggestion": "socar-hipass-insurance-guide",
      "queries": [
        "쏘카 하이 패스",
        "쏘카 보험 디시",
        "쏘카 이용 방법"
      ],
      "total_impressions": 1520,
      "seasonal_index": 0.9,
      "is_trending": false,
      "rationale": "하이패스와 보험에 대한 정보로 사용자 편의성 증대"
    },
    {
      "title": "쏘카 비즈니스: 기업용 카셰어링 서비스 완벽 가이드",
      "slug_suggestion": "socar-business-guide",
      "queries": [
        "쏘카 비즈니스",
        "쏘카 장기 렌트",
        "쏘카 이용 방법"
      ],
      "total_impressions": 1360,
      "seasonal_index": 0.83,
      "is_trending": false,
      "rationale": "기업 고객을 위한 맞춤형 정보 제공으로 B2B 시장 공략"
    },
    {
      "title": "쏘카 고객센터 이용 가이드: 빠른 문제 해결을 위한 팁",
      "slug_suggestion": "socar-customer-service-guide",
      "queries": [
        "쏘카 고객센터",
        "쏘카 고객 센터",
        "쏘카 고객센터 전화번호"
      ],
      "total_impressions": 1660,
      "seasonal_index": 0.87,
      "is_trending": false,
      "rationale": "고객 지원 관련 정보를 종합하여 사용자 만족도 향상"
    },
    {
      "title": "쏘카 스포츠카 & 고급차 이용 가이드: 포르쉐부터 아반떼N까지",
      "slug_suggestion": "socar-luxury-sports-car-guide",
      "queries": [
        "쏘카 포르쉐",
        "쏘카 아반떼n",
        "쏘카 아반떼 n"
      ],
      "total_impressions": 1640,
      "seasonal_index": 0.67,
      "is_trending": false,
      "rationale": "프리미엄 차량 이용에 대한 관심 충족 및 고급 사용자층 유치"
    },
    {
      "title": "쏘카 초보 운전자 가이드: 면허 1년 미만도 안전하게",
      "slug_suggestion": "socar-beginner-driver-guide",
      "queries": [
        "쏘카 면허 1년 미만",
        "쏘카 이용 방법",
        "쏘카 나이"
      ],
      "total_impressions": 1430,
      "seasonal_index": 0.87,
      "is_trending": false,
      "rationale": "초보 운전자를 위한 맞춤 정보로 신규 사용자 유치 및 안전 운전 장려"
    }
  ],
  "topics_category": [
    {
      "title": "제주도 차박 명소 5선 + 안전한 차박 꿀팁",
      "slug_suggestion": "socar-tip-jeju-chabak-spots",
      "queries": [
        "제주도 차박",
        "제주 차박 명소",
        "차박 안전수칙"
      ],
      "total_impressions": 12000,
      "seasonal_index": 1.4,
      "is_trending": true,
      "rationale": "여름 휴가 시즌 제주 여행 수요 증가, 차박 트렌드와 연계"
    },
    {
      "title": "부산 해운대 근처 드라이브 코스 추천",
      "slug_suggestion": "socar-tip-busan-haeundae-drive",
      "queries": [
        "부산 드라이브 코스",
        "해운대 드라이브",
        "부산 여행"
      ],
      "total_impressions": 15000,
      "seasonal_index": 1.2,
      "is_trending": true,
      "rationale": "여름 휴가지로 인기 높은 부산 여행 수요 반영"
    },
    {
      "title": "강원도 캠핑카 여행 추천 코스 및 주의사항",
      "slug_suggestion": "socar-tip-gangwon-camper-van",
      "queries": [
        "강원도 캠핑카",
        "캠핑카 여행",
        "캠핑카 대여"
      ],
      "total_impressions": 8000,
      "seasonal_index": 1.3,
      "is_trending": true,
      "rationale": "봄~여름 캠핑 시즌, 캠핑카 여행 트렌드 반영"
    },
    {
      "title": "경주 1박2일 자동차 여행 코스 완벽 가이드",
      "slug_suggestion": "socar-tip-gyeongju-2day-trip",
      "queries": [
        "경주 여행 코스",
        "경주 자동차 여행",
        "경주 1박2일"
      ],
      "total_impressions": 10000,
      "seasonal_index": 1.1,
      "is_trending": false,
      "rationale": "봄~가을 인기 여행지 경주, 주말 여행 수요 반영"
    },
    {
      "title": "전주 한옥마을 근처 주차장 & 맛집 투어 코스",
      "slug_suggestion": "socar-tip-jeonju-hanok-parking-food",
      "queries": [
        "전주 한옥마을 주차",
        "전주 맛집",
        "전주 당일치기"
      ],
      "total_impressions": 9000,
      "seasonal_index": 1.0,
      "is_trending": false,
      "rationale": "연중 인기 여행지 전주, 주차 정보 니즈 반영"
    },
    {
      "title": "서울 근교 드라이브 스루 맛집 & 카페 8선",
      "slug_suggestion": "socar-tip-seoul-drive-thru",
      "queries": [
        "드라이브 스루 맛집",
        "서울 근교 드라이브",
        "드라이브 카페"
      ],
      "total_impressions": 7000,
      "seasonal_index": 1.2,
      "is_trending": true,
      "rationale": "일상 속 근거리 드라이브 수요 반영, 드라이브 스루 트렌드"
    },
    {
      "title": "차박 초보를 위한 필수 준비물 & 꿀팁 모음",
      "slug_suggestion": "socar-tip-chabak-beginner-guide",
      "queries": [
        "차박 준비물",
        "차박 초보",
        "차박 꿀팁"
      ],
      "total_impressions": 11000,
      "seasonal_index": 1.3,
      "is_trending": true,
      "rationale": "봄~가을 차박 수요 증가, 초보 가이드 필요성 반영"
    },
    {
      "title": "제주도 1달 살기 꿀팁 & 렌트카 장기 이용 안내",
      "slug_suggestion": "socar-tip-jeju-long-stay",
      "queries": [
        "제주도 한달 살기",
        "제주 장기 렌트카",
        "제주 한달 살기 팁"
      ],
      "total_impressions": 6000,
      "seasonal_index": 1.1,
      "is_trending": false,
      "rationale": "장기 체류형 여행 트렌드, 제주 장기 렌트 수요 반영"
    },
    {
      "title": "서울 근교 당일치기 드라이브 코스 추천 5선",
      "slug_suggestion": "socar-tip-seoul-day-trip",
      "queries": [
        "서울 근교 당일치기",
        "당일치기 드라이브",
        "서울 근교 나들이"
      ],
      "total_impressions": 13000,
      "seasonal_index": 1.2,
      "is_trending": true,
      "rationale": "주말 근거리 여행 수요 증가, 당일치기 트렌드 반영"
    }
  ]
};