// auto-generated by SEO refresh agent
// last_updated: 2026-05-11

const SEO_DATA = {
  "meta": {
    "lastUpdated": "2026-05-11",
    "period7d": "2026-05-04 ~ 2026-05-11",
    "period28d": "2026-04-13 ~ 2026-05-11",
    "totalBlogPages": 4
  },
  "performance": {
    "summary": {
      "totalImpressions": 1909,
      "totalClicks": 45,
      "avgPosition": 6.8,
      "avgCTR": 4.6
    },
    "pages": [
      {
        "url": "https://www.socar.kr/blog/socar-tip-2daysdriving",
        "slug": "socar-tip-2daysdriving",
        "position": 3.9,
        "impressions": 1342,
        "clicks": 20,
        "ctr": 1.5,
        "queries": [
          "쏘카 1박 2일 비용",
          "쏘카 가격표",
          "쏘카 suv 1시간 요금",
          "쏘카 전기차 주행요금",
          "쏘카 비용"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-travel-busan-gyeongnam-ulsan-festival-2026",
        "slug": "socar-travel-busan-gyeongnam-ulsan-festival-2026",
        "position": 14.7,
        "impressions": 307,
        "clicks": 6,
        "ctr": 2.0,
        "queries": [
          "봄에 하는 축제",
          "부산 여행",
          "4월 축제",
          "게임 로고를 만드는 방법",
          "더 스카우트 인 부산"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-9900won-commute-tip",
        "slug": "socar-9900won-commute-tip",
        "position": 4.7,
        "impressions": 152,
        "clicks": 10,
        "ctr": 6.6,
        "queries": [
          "쏘카 기름값",
          "쏘카 실속보장",
          "쏘카 당일최저가",
          "쏘카 퇴출근 쿠폰",
          "쏘카 6시간 가격"
        ]
      },
      {
        "url": "https://www.socar.kr/blog/socar-delivery-complete-guide",
        "slug": "socar-delivery-complete-guide",
        "position": 3.7,
        "impressions": 108,
        "clicks": 9,
        "ctr": 8.3,
        "queries": [
          "쏘카 배달",
          "쏘카 24시간 무료 쿠폰",
          "쏘카 배달 요청사항",
          "쏘카 예약 시간보다 일찍",
          "쏘카 예약시간보다 일찍"
        ]
      }
    ],
    "history": [
      {
        "week": "2026-05-11",
        "totalImpressions": 4610,
        "totalClicks": 136
      }
    ]
  },
  "refresh": [
    {
      "url": "https://www.socar.kr/blog/socar-travel-busan-gyeongnam-ulsan-festival-2026",
      "position": 14.7,
      "impressions": 307,
      "clicks": 6,
      "ctr": 2.0,
      "queries": [
        "봄에 하는 축제",
        "2026년 봄 축제",
        "4 월 16 일",
        "4월 31일",
        "4월 축제"
      ],
      "analysis": "[T1] 리드문: ✅\n- 적절한 리드문으로 시작하여 글의 주제와 내용을 잘 요약하고 있습니다.\n\n[T2] H2 개수: ✅ \n- 5개의 H2 제목을 사용하여 내용을 잘 구조화했습니다.\n\n[T3] 질문형 H2: ⚠️\n- H2 제목 중 하나만 질문형입니다. \"어떤 축제가 열리나요?\" 외에 1-2개 더 질문형 H2를 추가하면 좋겠습니다.\n\n[T4] 키워드 배치: ⚠️\n- 주요 키워드인 \"봄 축제\", \"4월 축제\", \"5월 축제\" 등의 사용을 늘리고, 특히 H2, H3 제목에 더 자주 포함시키면 좋겠습니다.\n\n[T5] 분량: ✅\n- 충분한 분량으로 각 축제에 대해 상세히 설명하고 있습니다.\n\n[T7] 구조: ✅\n- 표, 이미지, 굵은 글씨 등을 활용해 가독성 높은 구조로 작성되었습니다.\n\n보강 제안:\n1. 질문형 H2 제목 1-2개 추가 (예: \"부산·경남·울산 봄 축제, 어떻게 즐기면 좋을까요?\")\n2. 주요 키워드를 H2, H3 제목에 더 자주 포함 (예: \"2026년 4월-5월 부산 봄 축제 총정리\")\n3. 각 축제 설명 끝에 간단한 CTA(Call-to-Action) 추가 (예: \"지금 바로 쏘카로 김해 가야문화축제 방문하기\")"
    }
  ],
  "topics_brand": [],
  "topics_category": []
};